### PR TITLE
Restore changes from 0.4.2-12

### PR DESCRIPTION
**Pull request by jbicha**
Drop Ubuntu-specific gksu dependency and patch (Closes: #[894175](https://bugs.debian.org/894175))
Drop unnecessary dirs files

### CODE REVIEW

**Comment by kravemir** [comment]
@jbicha I'm currently on a business trip (for the whole week), so I don't have access to private computers to test it. I'll take a look on it on the weekend.

**Comment by jbicha** [comment]
No problem. It's not blocking me because I went ahead and pushed it to Ubuntu yesterday (because it's late in Ubuntu's release cycle).

**Comment by kravemir** [comment]
> pushed it to Ubuntu yesterday (because it's late in Ubuntu's release cycle).

What do you mean by that? If you want to push it into 18.04, then please add at least patch from ArchLinux package: https://aur.archlinux.org/packages/ddccontrol/ . Otherwise, it gddccontrol won't work by default without any indication why (and, Ubuntu users aren't always very technically skilled).

From `PKGBUILD`:

```bash
  # policykit
  install -Dm644 \
    "$srcdir/org.ddccontrol.pkexec.gddccontrol.policy" \
    "${pkgdir}/usr/share/polkit-1/actions/org.ddccontrol.pkexec.gddccontrol.policy"
  sed -e 's/Exec=gddccontrol/Exec=pkexec gddccontrol/' \
    -i "${pkgdir}/usr/share/applications/gddccontrol.desktop"
```

And, patch for `org.ddccontrol.pkexec.gddccontrol.policy`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>DDCcontrol</vendor>
  <vendor_url>http://ddccontrol.sourceforge.net/</vendor_url>

  <action id="org.ddccontrol.pkexec.gddccontrol">
    <message>Authentication is required to run the Monitor Settings</message>
    <icon_name>gddccontrol</icon_name>
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/gddccontrol</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>

</policyconfig>
```

**Comment by jbicha** [comment]
What I mean is that Ubuntu 18.04 LTS will release in only a week and a half. I'm proposing removing gksu from the Ubuntu repositories so I was in a hurry.

Let me know if you have time this weekend to push this update to Debian so I can sync. Otherwise I can just upload your proposal to Ubuntu directly without waiting. Since it's in "unseeded universe", I can push an update to Ubuntu as late as next week Wednesday.

**Comment by kravemir** [comment]
@jbicha I've sent you email directly in order to clarify things, so I can work on it in the weekend, and I'm not blocked.

I see, that you pushed it to ubuntu as `0.4.3-1ubuntu1`. So, I'm merging this to repository as `UNRELEASED`.

Also, I would like to add `pkexec` (for both Debian and Ubuntu) as replacement for `gksu` (only Ubuntu specific, now).

The `pkexec` will be removed once new version of ddccontrol gets released with D-Bus daemon. See: https://github.com/ddccontrol/ddccontrol/blob/master/CHANGELOG.md. The functionality is implemented, but it needs some polishing. Mainly, daemon is a long-lived process, and I want to make sure, that there are no memory leaks in it.

**Pull request merged**
